### PR TITLE
Updates to allow creating a SteamOS chroot

### PR DESCRIPTION
**Pull request by Ryochan7**
For messing around with building programs on SteamOS, I would prefer to use a clean chroot instead of possibly messing up my main system. Although build-test-chroot.sh was able to create a Debian chroot, it would error out when attempting to create a SteamOS chroot.

A few changes needed to be made to get around the errors encountered. One tricky problem was that the Valve keyring needed to be specified when running debootstrap or the program would exit saying that the release uses an unknown key. Some of the other changes were just to update the script from using wheezy and alchemist for the releases to jessie and brewmaster. Some extra config files have been added and the binding of /dev/pts has been moved.

One thing that might need to be checked is regarding the command line flags being used. In the usage, it says that `-type debian` would be used to create a Debian chroot although the script would have required `-type jessie`. I made the change so that **debian** would be the proper target type again with jessie being assigned as the release.

### CODE REVIEW

**Comment by madmodderx** [comment]
That was probably me, I apologize. I was just trying pull an updated
brewmaster branch. the instructions weren't very clear on how to grab a new
branch and it asked for id.

Again apologies

**Comment by ProfessorKaos64** [comment]
I'll check the option flags and merge this today. This was a "start a basic idea" and I never got 100% into it. I wanted it to eventually be as you have now @Ryochan7 , a testing chroot for SteamOS. @madmodderx , if you meant to post in this issues post, the README.MD notes to go into the wiki for all documents. I will update the page for this today.

**Comment by ProfessorKaos64** [comment]
@Ryochan7 , I did a lot of restructuring this morning. Make sure to check out both the main script and the post-install script that gets called. The intention is to allow Debian wheezy/jessie, or SteamOS / SteamOS beta alchemist/brewmaster. I am still working on things, so give me about an hour yet.

**Comment by ProfessorKaos64** [comment]
@Ryochan7 I do change the sources list [here](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/scriptmodules/chroot-post-install.sh#L175) for brewmaster, since what is provided as part of the chroot process is missing the typical source configuration of a standard SteamOS install. The line is for brewmaster though. Do you think there is a way to request alchemist sources from repo.steamstatic.com ?

**Comment by ProfessorKaos64** [comment]
@Ryochan7 The massive restructuring I did today should be 90% complete. I tested Debian Wheezy/Jessie, and SteamOS. Besides retrofitting alchemist in here, things are looking good.

**Pull request merged**
