### PR TITLE
Changes to allow UE4 install script to work

### PR DESCRIPTION
**Pull request by Ryochan7**
Thank you for the fantastic set of scripts. I have only started messing with them and they are already proving to be extremely useful.

This set of changes was needed in order for the ue4 install script to work. The changes include downloading the newest alpha package, some changes in variable usage, and only having package validation occur if $software_list has been defined and is not empty. The change in desktop-software.sh was needed since cat would always stop the script from continuing until C-c was entered.

### CODE REVIEW

**Comment by ProfessorKaos64** [comment]
Thank you so much @Ryochan7 I'm a fan of antimicro a ton. I appreciate the help wholeheartedly. I like to tinker, and it's nice that a few people like what i'm trying to do here. The code looks good for the desktop-software.sh rewrite. Any particular reason single brackets vs. double brackets is used? I can assume you tested this already. I'll just run through a few tests and merge this in later tonight. I can never seem to reach the download page for UE4's alpha without it going blank after I login anymore. So...I usually cheat by peaking at the Arch Linux package :)

Again, appreciate the help very much.

**Comment by ProfessorKaos64** [comment]
Added your contributions to the AUTHORS.md file as well.

**Comment by Ryochan7** [comment]
I am more used to using [ instead of [[ when writing tests in bash scripts. For that test, I don't think that it should make a difference which one is used. I will keep in mind to use [[ for any future changes.

C-c is just a shorthand way of saying Ctrl+c.

**Comment by ProfessorKaos64** [comment]
I did test some batch installs and 1 package, and then multiple packages, so the code seems fine. If it works, I may just keep the double bracket test to keep it consistent. Maybe personal preference ha.  Thanks a bunch Ryochan.

**Pull request merged**
